version: "3"

services:
  web:
    image: caddy:2.4.3
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      # persistent data for caddy
      - web_data:/data

  backend:
    build: ./dockerfiles
    image: backend
    volumes:
      # Mount code in working dir
      - .:/app
    working_dir: /app

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: backend
      MYSQL_DATABASE: backend
      MYSQL_USER: backend
      MYSQL_PASSWORD: backend
    volumes:
      - db_data:/var/lib/db_data

volumes:
  web_data:
  db_data:
